import React, { useState, useEffect, useCallback, useRef } from "react";
import { GameTheme, ScoreRecord } from "../types";
import {
  ArrowLeft,
  RefreshCw,
  Trophy,
  Zap,
  RotateCcw,
  Eraser,
  PenTool,
  HelpCircle,
  Eye,
  EyeOff,
  AlertTriangle,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import confetti from "canvas-confetti";

interface SudokuProps {
  theme: GameTheme;
  onGoBack: () => void;
  userNickname: string;
  onConsumeEntropy?: (points: number) => void;
  onScoreSubmit?: (score: ScoreRecord) => void;
  initialDifficulty?: "easy" | "medium" | "hard";
}

type Cell = {
  value: number; // 0 means empty
  original: boolean; // true if generated by server/config, false represents user-set
  notes: number[]; // array of small notes in the cell
  error: boolean; // simple instant conflict tracker
};

type Board = Cell[][];

// Base mathematically perfect Sudoku solution used for scrambling
const SEED_BOARD = [
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [4, 5, 6, 7, 8, 9, 1, 2, 3],
  [7, 8, 9, 1, 2, 3, 4, 5, 6],
  [2, 3, 4, 5, 6, 7, 8, 9, 1],
  [5, 6, 7, 8, 9, 1, 2, 3, 4],
  [8, 9, 1, 2, 3, 4, 5, 6, 7],
  [3, 4, 5, 6, 7, 8, 9, 1, 2],
  [6, 7, 8, 9, 1, 2, 3, 4, 5],
  [9, 1, 2, 3, 4, 5, 6, 7, 8],
];

// Generates billions of unique mathematically compliant Sudoku grids
function generateSudoku(diff: "easy" | "medium" | "hard"): {
  solution: number[][];
  initial: number[][];
} {
  // 1. Setup base grid clone
  let grid = SEED_BOARD.map((row) => [...row]);

  // 2. Relabel numbers randomly (1-9 permutation)
  const nums = [1, 2, 3, 4, 5, 6, 7, 8, 9];
  const shuffledNums = [...nums].sort(() => Math.random() - 0.5);
  const mapping: Record<number, number> = {};
  nums.forEach((val, index) => {
    mapping[val] = shuffledNums[index];
  });

  for (let r = 0; r < 9; r++) {
    for (let c = 0; c < 9; c++) {
      grid[r][c] = mapping[grid[r][c]];
    }
  }

  // Helper to shuffle list
  const shuffle = <T,>(arr: T[]): T[] =>
    [...arr].sort(() => Math.random() - 0.5);

  // 3. Scramble rows within each 3x3 block
  const rowBlocks = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
  ];
  const scrambledRowsResult: number[][] = Array(9)
    .fill(null)
    .map(() => []);
  rowBlocks.forEach((block) => {
    const perm = shuffle(block);
    perm.forEach((oldRow, i) => {
      scrambledRowsResult[block[i]] = [...grid[oldRow]];
    });
  });
  grid = scrambledRowsResult;

  // 4. Scramble columns within each 3x3 block
  const colBlocks = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
  ];
  const scrambledColsResult: number[][] = Array(9)
    .fill(null)
    .map(() => Array(9).fill(0));
  colBlocks.forEach((block) => {
    const perm = shuffle(block);
    for (let r = 0; r < 9; r++) {
      perm.forEach((oldCol, i) => {
        scrambledColsResult[r][block[i]] = grid[r][oldCol];
      });
    }
  });
  grid = scrambledColsResult;

  // 5. Scramble block bands (rows bands)
  const rowBandPerm = shuffle([0, 1, 2]);
  const bandScrambledGrid: number[][] = [];
  rowBandPerm.forEach((band) => {
    const startIndex = band * 3;
    bandScrambledGrid.push([...grid[startIndex]]);
    bandScrambledGrid.push([...grid[startIndex + 1]]);
    bandScrambledGrid.push([...grid[startIndex + 2]]);
  });
  grid = bandScrambledGrid;

  // 6. Transpose with 50% chance
  if (Math.random() > 0.5) {
    const transposed: number[][] = Array(9)
      .fill(null)
      .map(() => Array(9).fill(0));
    for (let r = 0; r < 9; r++) {
      for (let c = 0; c < 9; c++) {
        transposed[c][r] = grid[r][c];
      }
    }
    grid = transposed;
  }

  // Save full solution
  const solution = grid.map((row) => [...row]);

  // 7. Carve holes based on difficulty
  // Easy: ~35-40 holes (leaves ~41-46 clues)
  // Medium: ~46-51 holes (leaves ~30-35 clues)
  // Hard: ~54-58 holes (leaves ~23-27 clues)
  let holesToCarve = 38;
  if (diff === "medium") holesToCarve = 48;
  if (diff === "hard") holesToCarve = 55;

  const initial = grid.map((row) => [...row]);

  // List of all 81 positions
  const positions: [number, number][] = [];
  for (let r = 0; r < 9; r++) {
    for (let c = 0; c < 9; c++) {
      positions.push([r, c]);
    }
  }

  // Shuffle positions and carve
  const shuffledPositions = shuffle(positions);
  let carved = 0;
  for (const [r, c] of shuffledPositions) {
    if (carved >= holesToCarve) break;
    initial[r][c] = 0;
    carved++;
  }

  return { solution, initial };
}

export default function Sudoku({
  theme,
  onGoBack,
  userNickname,
  onConsumeEntropy,
  onScoreSubmit,
  initialDifficulty = "medium",
}: SudokuProps) {
  const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">(
    initialDifficulty
  );
  const [board, setBoard] = useState<Board>(() =>
    Array(9)
      .fill(null)
      .map(() =>
        Array(9)
          .fill(null)
          .map(() => ({ value: 0, original: false, notes: [], error: false }))
      )
  );
  const [solutionGrid, setSolutionGrid] = useState<number[][]>([]);
  const [selectedCell, setSelectedCell] = useState<{
    r: number;
    c: number;
  } | null>(null);

  const [notesMode, setNotesMode] = useState<boolean>(false);
  const [autoHighlightErrors, setAutoHighlightErrors] = useState<boolean>(true);

  // Game states
  const [timer, setTimer] = useState<number>(0);
  const [isCompleted, setIsCompleted] = useState<boolean>(false);
  const [hasConsumedEntropy, setHasConsumedEntropy] = useState<boolean>(false);
  const [mistakes, setMistakes] = useState<number>(0);

  // Undo engine stack
  const [history, setHistory] = useState<string[]>([]); // Serialized JSON of broad boards

  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Core trigger to initialize or reset Sudoku
  const initGame = useCallback(
    (diffToUse: "easy" | "medium" | "hard" = difficulty) => {
      const { solution, initial } = generateSudoku(diffToUse);
      setSolutionGrid(solution);

      const initialBoard: Board = initial.map((row, r) =>
        row.map((val, c) => ({
          value: val,
          original: val !== 0,
          notes: [],
          error: false,
        }))
      );

      setBoard(initialBoard);
      setSelectedCell(null);
      setTimer(0);
      setIsCompleted(false);
      setHasConsumedEntropy(false);
      setMistakes(0);
      setHistory([]);

      // Restart timer
      if (timerRef.current) clearInterval(timerRef.current);
      timerRef.current = setInterval(() => {
        setTimer((t) => t + 1);
      }, 1000);
    },
    [difficulty]
  );

  // Initial Boot
  useEffect(() => {
    initGame(initialDifficulty);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [initialDifficulty, initGame]);

  // Checks conflicts on the current grid
  const recomputeConflictsAndStatus = useCallback(
    (currBoard: Board, displayErrors: boolean) => {
      const updated = currBoard.map((row) =>
        row.map((cell) => ({ ...cell, error: false }))
      );

      if (displayErrors) {
        // 1. Check Row conflicts
        for (let r = 0; r < 9; r++) {
          const counts: Record<number, number[]> = {};
          for (let c = 0; c < 9; c++) {
            const val = updated[r][c].value;
            if (val > 0) {
              if (!counts[val]) counts[val] = [];
              counts[val].push(c);
            }
          }
          Object.entries(counts).forEach(([valStr, cols]) => {
            if (cols.length > 1) {
              cols.forEach((c) => {
                updated[r][c].error = true;
              });
            }
          });
        }

        // 2. Check Column conflicts
        for (let c = 0; c < 9; c++) {
          const counts: Record<number, number[]> = {};
          for (let r = 0; r < 9; r++) {
            const val = updated[r][c].value;
            if (val > 0) {
              if (!counts[val]) counts[val] = [];
              counts[val].push(r);
            }
          }
          Object.entries(counts).forEach(([valStr, rows]) => {
            if (rows.length > 1) {
              rows.forEach((r) => {
                updated[r][c].error = true;
              });
            }
          });
        }

        // 3. Check 3x3 Box conflicts
        for (let boxRow = 0; boxRow < 3; boxRow++) {
          for (let boxCol = 0; boxCol < 3; boxCol++) {
            const counts: Record<number, { r: number; c: number }[]> = {};
            for (let i = 0; i < 3; i++) {
              for (let j = 0; j < 3; j++) {
                const r = boxRow * 3 + i;
                const c = boxCol * 3 + j;
                const val = updated[r][c].value;
                if (val > 0) {
                  if (!counts[val]) counts[val] = [];
                  counts[val].push({ r, c });
                }
              }
            }
            Object.entries(counts).forEach(([valStr, cells]) => {
              if (cells.length > 1) {
                cells.forEach(({ r, c }) => {
                  updated[r][c].error = true;
                });
              }
            });
          }
        }
      }

      // 4. Check if fully solved and matches the solution
      let solved = solutionGrid.length === 9;
      if (solved) {
        for (let r = 0; r < 9; r++) {
          for (let c = 0; c < 9; c++) {
            if (
              !solutionGrid[r] ||
              updated[r][c].value !== solutionGrid[r][c]
            ) {
              solved = false;
            }
          }
        }
      }

      if (solved && !isCompleted && solutionGrid.length > 0) {
        setIsCompleted(true);
        if (timerRef.current) clearInterval(timerRef.current);

        // Blast Confetti
        confetti({
          particleCount: 150,
          spread: 80,
          origin: { y: 0.6 },
        });
      }

      return updated;
    },
    [solutionGrid, isCompleted]
  );

  // Saves current Board state to history before editing
  const saveHistory = (currBoard: Board) => {
    const raw = JSON.stringify(currBoard);
    setHistory((prev) => {
      // Keep max 35 states
      const next = [...prev, raw];
      if (next.length > 35) next.shift();
      return next;
    });
  };

  // Undo Action
  const handleUndo = () => {
    if (history.length === 0) return;
    const nextHistory = [...history];
    const prevRaw = nextHistory.pop()!;
    setHistory(nextHistory);

    const prevBoard = JSON.parse(prevRaw) as Board;
    setBoard(recomputeConflictsAndStatus(prevBoard, autoHighlightErrors));
  };

  // Set grid value
  const setCellValue = (val: number) => {
    if (!selectedCell || isCompleted) return;
    const { r, c } = selectedCell;
    const cell = board[r][c];
    if (cell.original) return; // Cannot edit originals

    // Save state to undo engine
    saveHistory(board);

    const nextBoard = board.map((row, ri) =>
      row.map((col, ci) => {
        if (ri === r && ci === c) {
          if (notesMode) {
            // Pencil Notes Mode
            if (val === 0) {
              return { ...col, value: 0, notes: [] }; // Eraser removes notes too
            }
            const notes = col.notes.includes(val)
              ? col.notes.filter((n) => n !== val)
              : [...col.notes, val].sort();
            return { ...col, value: 0, notes }; // Notes empty out the main value
          } else {
            // Main Standard placement
            const isIncorrect = val !== 0 && solutionGrid[r]?.[c] !== val;
            if (isIncorrect) {
              setMistakes((m) => m + 1);
            }
            return { ...col, value: val, notes: [], error: false };
          }
        }
        return col;
      })
    );

    setBoard(recomputeConflictsAndStatus(nextBoard, autoHighlightErrors));
  };

  // Keyboard support for entry
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (isCompleted || !selectedCell) return;
      if (e.key >= "1" && e.key <= "9") {
        setCellValue(parseInt(e.key, 10));
      } else if (e.key === "Backspace" || e.key === "Delete" || e.key === "0") {
        setCellValue(0);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [selectedCell, board, notesMode, isCompleted]);

  // Give Hints (reveals cell solving value)
  const handleHint = () => {
    if (!selectedCell || isCompleted) return;
    const { r, c } = selectedCell;
    if (board[r][c].original) return;

    saveHistory(board);

    const correctVal = solutionGrid[r]?.[c] || 0;
    const nextBoard = board.map((row, ri) =>
      row.map((col, ci) => {
        if (ri === r && ci === c) {
          return { ...col, value: correctVal, notes: [], error: false };
        }
        return col;
      })
    );

    setBoard(recomputeConflictsAndStatus(nextBoard, autoHighlightErrors));
    // Cost some virtual seconds as minor helper penalty
    setTimer((t) => t + 15);
  };

  // Switch difficulty dynamically
  const handleDiffChange = (diffToUse: "easy" | "medium" | "hard") => {
    setDifficulty(diffToUse);
    initGame(diffToUse);
  };

  // Handle auto-highlight changes
  useEffect(() => {
    setBoard((prev) => recomputeConflictsAndStatus(prev, autoHighlightErrors));
  }, [autoHighlightErrors, recomputeConflictsAndStatus]);

  // Entropy calculation on win
  useEffect(() => {
    if (!isCompleted || hasConsumedEntropy) return;
    if (onConsumeEntropy) {
      setHasConsumedEntropy(true);
      const baseReward =
        difficulty === "easy" ? 35 : difficulty === "medium" ? 50 : 80;
      onConsumeEntropy(baseReward);
    }

    // Log record
    if (onScoreSubmit) {
      const record: ScoreRecord = {
        id: `score_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
        userId: "temp_user",
        nickname: userNickname,
        avatarColor: "emerald",
        avatarEmoji: "🧠",
        game: "sudoku",
        mode: "sudoku",
        difficulty: `数独 [${difficulty === "easy" ? "初级" : difficulty === "medium" ? "中级" : "高级"}]`,
        time: timer,
        createdAt: Date.now(),
      };
      onScoreSubmit(record);
    }
  }, [
    isCompleted,
    hasConsumedEntropy,
    timer,
    difficulty,
    onConsumeEntropy,
    onScoreSubmit,
    userNickname,
  ]);

  // Help selection calculations
  const rSelected = selectedCell?.r;
  const cSelected = selectedCell?.c;
  const valSelected =
    rSelected !== undefined && cSelected !== undefined
      ? board[rSelected][cSelected].value
      : null;

  const isInSymmetricBox = (
    r1: number,
    c1: number,
    r2: number,
    c2: number
  ): boolean => {
    return (
      Math.floor(r1 / 3) === Math.floor(r2 / 3) &&
      Math.floor(c1 / 3) === Math.floor(c2 / 3)
    );
  };

  const getCellHighlightClass = (r: number, c: number): string => {
    if (!selectedCell) return "";
    const isS = rSelected === r && cSelected === c;
    if (isS) {
      return false
        ? "bg-amber-500/25 border-amber-600 border-2 scale-[1.02] z-10 shadow-md text-amber-900"
        : "bg-emerald-500/35 border-emerald-400 border-2 scale-[1.02] z-10 shadow-lg";
    }

    // Check row/col or box matching
    const inBox = isInSymmetricBox(r, c, rSelected!, cSelected!);
    const inRowCol = rSelected === r || cSelected === c;

    const highlightColor = false
      ? "bg-amber-600/5"
      : theme.id === "cyberpunk"
        ? "bg-amber-500/10"
        : "bg-emerald-500/8";

    if (valSelected && board[r][c].value === valSelected) {
      return false
        ? "bg-amber-500/20 font-extrabold scale-[1.01] ring-1 ring-amber-500/30 text-amber-900 shadow-sm"
        : "bg-emerald-500/20 font-extrabold scale-[1.01] ring-1 ring-emerald-500/30";
    }

    if (inRowCol || inBox) {
      return highlightColor;
    }
    return "";
  };

  // Convert seconds to clean display format "00:00"
  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  };

  return (
    <div
      className={`w-full flex flex-col gap-4 select-none ${"text-zinc-303"}`}
    >
      {/* Sub Header */}
      <div
        className={`flex flex-row items-center justify-between pb-3.5 border-b w-full px-1 gap-2 ${"border-zinc-800/60"}`}
      >
        <button
          onClick={onGoBack}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition-all text-xs font-semibold cursor-pointer active:scale-95 shrink-0 ${"bg-zinc-800/60 border border-zinc-700/50 hover:bg-zinc-800 hover:text-white text-zinc-300"}`}
        >
          <ArrowLeft size={13} />
          <span>返回大厅</span>
        </button>

        <div className="flex items-center gap-1.5 min-w-0">
          <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse shrink-0" />
          <span
            className={`text-[10px] sm:text-[11px] font-mono tracking-wider block uppercase font-bold truncate ${"text-zinc-405"}`}
          >
            <span className="hidden sm:inline">
              经典数独 (Sudoku) - 链式数字逻辑训练
            </span>
            <span className="inline sm:hidden">经典数独 (Sudoku)</span>
          </span>
        </div>
      </div>

      {/* Control panel & difficulty options */}
      <div
        className={`grid grid-cols-1 md:grid-cols-2 gap-3 p-3 rounded-xl border ${"bg-zinc-900/35 border-zinc-850/40"}`}
      >
        <div
          className={`flex items-center justify-between gap-2.5 p-2 rounded-lg border ${"bg-zinc-950/25 border border-zinc-900/65"}`}
        >
          <span
            className={`text-xs font-bold font-mono tracking-wide shrink-0 ${"text-zinc-400"}`}
          >
            难度级别:
          </span>
          <div className="flex items-center gap-1.5">
            {(
              [
                { id: "easy", label: "小白" },
                { id: "medium", label: "标配" },
                { id: "hard", label: "大师" },
              ] as const
            ).map((opt) => (
              <button
                key={`opt-diff-${opt.id}`}
                onClick={() => handleDiffChange(opt.id)}
                className={`py-1 px-3 rounded text-[10.5px] font-mono font-bold transition-all cursor-pointer ${
                  difficulty === opt.id
                    ? "bg-emerald-500/25 text-emerald-300 ring-1 ring-emerald-500/50 font-black shadow"
                    : "bg-zinc-900/40 hover:bg-[#2A2A2A] text-zinc-400"
                }`}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </div>

        <div
          className={`flex items-center justify-between gap-2.5 p-2 rounded-lg border text-xs font-mono ${"bg-zinc-950/25 border border-zinc-900/65 text-zinc-400 font-mono"}`}
        >
          <div className="flex items-center gap-2">
            <span>实时检查冲突:</span>
            <button
              onClick={() => setAutoHighlightErrors(!autoHighlightErrors)}
              className={`p-1 px-2 text-[10px] rounded font-bold transition-all cursor-pointer ${
                autoHighlightErrors
                  ? "bg-red-500/15 text-red-500 border border-red-500/30"
                  : "bg-zinc-900 text-zinc-500 border border-zinc-800"
              }`}
            >
              {autoHighlightErrors ? "已开启" : "已关闭"}
            </button>
          </div>
          <div className="flex items-center gap-3">
            <span>
              错误次数:{" "}
              <strong
                className={
                  mistakes > 3
                    ? "text-rose-500 font-extrabold"
                    : "text-zinc-303"
                }
              >
                {mistakes}
              </strong>
            </span>
          </div>
        </div>
      </div>

      {/* Main Grid & Interactive Controls Container */}
      <div className="w-full flex flex-col lg:flex-row gap-6 md:gap-8 items-center lg:items-start justify-center py-2 max-w-5xl mx-auto">
        {/* Sudoku Board Wrapper */}
        <div className="relative flex justify-center w-full max-w-[96%] sm:max-w-[92%] md:max-w-[530px] lg:max-w-[560px] xl:max-w-[600px]">
          {/* Confetti Blast Winner Overlay */}
          <AnimatePresence>
            {isCompleted && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-black/85 rounded-2xl border border-emerald-500/40 backdrop-blur-sm p-4 text-center"
              >
                <div className="w-14 h-14 rounded-full bg-emerald-505/20 border border-emerald-400 flex items-center justify-center mb-3">
                  <Trophy
                    className="text-emerald-400 animate-bounce"
                    size={26}
                  />
                </div>
                <h3 className="text-lg font-black text-white tracking-wide">
                  恭喜！谜题解开
                </h3>
                <p className="text-xs text-zinc-400 mt-1 max-w-[280px]">
                  用时{" "}
                  <strong className="text-emerald-400">
                    {formatTime(timer)}
                  </strong>
                  ，不屈不挠地挑战了数字链极限！
                </p>

                {/* Reward Indicator */}
                <div className="mt-4 px-4 py-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-xs font-bold text-zinc-300 flex items-center gap-2">
                  <Zap className="text-amber-400 animate-pulse" size={13} />
                  <span>
                    释放负熵 -
                    {difficulty === "easy"
                      ? 35
                      : difficulty === "medium"
                        ? 50
                        : 80}{" "}
                    克
                  </span>
                </div>

                <div className="flex gap-2.5 mt-5">
                  <button
                    onClick={() => initGame(difficulty)}
                    className={`py-1.5 px-4 rounded-lg text-xs font-black shadow-md cursor-pointer active:scale-95 transition-all ${"bg-emerald-500 hover:bg-emerald-400 text-black"}`}
                  >
                    再来一局
                  </button>
                  <button
                    onClick={onGoBack}
                    className={`py-1.5 px-4 rounded-lg text-xs font-black shadow active:scale-95 transition-all ${"bg-zinc-800 hover:bg-zinc-700 hover:text-white text-zinc-300"}`}
                  >
                    返回
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* 9x9 Grid Layout */}
          <div
            className={`grid grid-cols-9 gap-px p-[3px] rounded-xl overflow-hidden shadow-2xl relative border w-full aspect-square ${"bg-zinc-850 border-zinc-800"}`}
          >
            {board.map((row, r) =>
              row.map((cell, c) => {
                const highlightClass = getCellHighlightClass(r, c);

                // Fine-tune grid boundaries inside 3x3 grids (right border, bottom border lines)
                const hasThickRight = c === 2 || c === 5;
                const hasThickBottom = r === 2 || r === 5;

                return (
                  <button
                    key={`cell-${r}-${c}`}
                    onClick={() => {
                      if (isCompleted) return;
                      setSelectedCell({ r, c });
                    }}
                    className={`aspect-square flex items-center justify-center relative text-base sm:text-xl md:text-2xl transition-all duration-150 rounded ${
                      cell.original
                        ? "bg-zinc-900/90 text-zinc-100 font-extrabold"
                        : "bg-zinc-950 text-emerald-400 font-bold hover:bg-zinc-900/50"
                    } ${highlightClass}`}
                    style={{
                      marginRight: hasThickRight ? "3px" : "0px",
                      marginBottom: hasThickBottom ? "3px" : "0px",
                    }}
                  >
                    {/* Pencil notes small grid */}
                    {cell.value === 0 && cell.notes.length > 0 ? (
                      <div className="absolute inset-0.5 grid grid-cols-3 gap-0.5 p-[1px] leading-none text-[8.5px] sm:text-[10px] md:text-[11px] text-zinc-500 font-mono tracking-tighter select-none pointer-events-none">
                        {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => (
                          <span
                            key={`note-${n}`}
                            className={`flex items-center justify-center ${
                              cell.notes.includes(n)
                                ? "text-amber-400 font-semibold"
                                : "opacity-0"
                            }`}
                          >
                            {n}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <span
                        className={
                          cell.error
                            ? "text-red-500 font-extrabold line-through scale-105 filter drop-shadow"
                            : ""
                        }
                      >
                        {cell.value > 0 ? cell.value : ""}
                      </span>
                    )}

                    {/* Left margin error indicator orb if error and not solved */}
                    {cell.error && (
                      <div className="absolute top-1 right-1 w-1.5 h-1.5 rounded-full bg-rose-500" />
                    )}
                  </button>
                );
              })
            )}
          </div>
        </div>

        {/* Input NumPad and action controls */}
        <div className="w-full max-w-[255px] sm:max-w-[275px] flex flex-col gap-2 scale-95 sm:scale-100 origin-top">
          {/* Header Stats directly inside controls */}
          <div
            className={`flex items-center justify-between px-2.5 py-1.5 rounded-xl border ${"bg-zinc-900/60 border border-zinc-800/80"}`}
          >
            <div
              className={`flex items-center gap-1.5 font-mono text-xs ${"text-zinc-500"}`}
            >
              <span>用时:</span>
              <strong className={`text-sm ${"text-white"}`}>
                {formatTime(timer)}
              </strong>
            </div>

            {/* Quick action buttons */}
            <div className="flex items-center gap-2">
              <button
                onClick={handleUndo}
                disabled={history.length === 0}
                className={`p-1.5 rounded border transition-all cursor-pointer disabled:opacity-30 disabled:pointer-events-none ${"bg-zinc-950 text-zinc-400 hover:text-white border-zinc-850 hover:bg-zinc-800"}`}
                title="撤销上一步操作"
              >
                <RotateCcw size={13} />
              </button>

              <button
                onClick={handleHint}
                disabled={
                  !selectedCell ||
                  (selectedCell &&
                    board[selectedCell.r][selectedCell.c].original)
                }
                className={`p-1.5 rounded border transition-all cursor-pointer disabled:opacity-30 disabled:pointer-events-none flex items-center gap-1 text-[10px] font-bold ${"bg-zinc-950 text-zinc-405 hover:text-amber-300 border-zinc-850 hover:bg-zinc-800"}`}
                title="揭晓本单元格正确数值 (+15秒罚时)"
              >
                <HelpCircle size={12} />
                <span>求助</span>
              </button>

              <button
                onClick={() => initGame(difficulty)}
                className={`p-1.5 rounded border transition-all cursor-pointer ${"bg-zinc-950 text-zinc-400 hover:text-white border-zinc-850 hover:bg-zinc-800"}`}
                title="完全重新加载本局"
              >
                <RefreshCw size={13} />
              </button>
            </div>
          </div>

          {/* Pencil/Notes Mode Toggle Box */}
          <button
            onClick={() => setNotesMode(!notesMode)}
            className={`w-full py-2 px-4 rounded-xl border font-bold flex items-center justify-between text-xs transition-all cursor-pointer ${
              notesMode
                ? "bg-amber-500/20 border-amber-500/80 text-amber-303 shadow-md ring-1 ring-amber-500/30"
                : "bg-zinc-900/40 border-zinc-800 text-zinc-400 hover:border-zinc-700/80"
            }`}
          >
            <div className="flex items-center gap-2">
              <PenTool
                size={14}
                className={notesMode ? "text-amber-400" : "text-zinc-500"}
              />
              <span>草稿模式 (Pencil Notes)</span>
            </div>
            <span
              className={`text-[9px] px-1.5 py-0.5 rounded-full font-black tracking-wider uppercase font-mono ${
                notesMode
                  ? "bg-amber-500/30 text-amber-303"
                  : "bg-zinc-900 text-zinc-650"
              }`}
            >
              {notesMode ? "ON" : "OFF"}
            </span>
          </button>

          {/* Virtual Numpad Grid */}
          <div className="grid grid-cols-3 gap-2">
            {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((num) => {
              return (
                <button
                  key={`num-pad-${num}`}
                  onClick={() => setCellValue(num)}
                  className={`py-2 px-1 hover:scale-105 active:scale-95 rounded-xl font-bold font-mono text-base sm:text-lg transition-all cursor-pointer shadow flex flex-col items-center justify-center relative group border ${
                    false
                      ? "bg-[#EFEADB] hover:bg-[#E1D6BF] border-[#DFD3C1] text-[#4F4639]"
                      : "bg-zinc-900/90 border border-zinc-800 text-white hover:bg-zinc-800 hover:text-emerald-400"
                  }`}
                >
                  <span>{num}</span>
                </button>
              );
            })}

            {/* Erase button spans full columns at bottom */}
            <button
              onClick={() => setCellValue(0)}
              className={`col-span-3 py-2 hover:scale-[1.02] active:scale-95 border rounded-xl font-bold text-xs flex items-center justify-center gap-1.5 transition-all cursor-pointer font-mono ${
                false
                  ? "bg-rose-500/10 hover:bg-rose-500/20 border-rose-300/60 text-rose-800"
                  : "bg-rose-500/10 hover:bg-rose-500/20 border border-rose-500/35 text-rose-300"
              }`}
            >
              <Eraser size={13} />
              <span>擦除内容 (Eraser)</span>
            </button>
          </div>

          <div
            className={`mt-1 p-2.5 rounded-lg border text-[10px] leading-normal flex items-start gap-1.5 ${"bg-zinc-955/40 border border-zinc-900 text-zinc-500"}`}
          >
            <AlertTriangle
              size={13}
              className={`${"text-zinc-650"} shrink-0 mt-0.5`}
            />
            <p>
              提示：高亮选中的网格支持键盘数字键输入，草稿模式下填写的数字会缩小展示，用于逻辑试错或多路链排除。
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
